import { CheckIcon } from "@radix-ui/react-icons";
import { ActivityIcon, BackpackIcon, ListTodoIcon } from "lucide-react";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/btero0aK9VK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export function KanbanPage() {
  return (
    <div key="1" className="flex flex-col h-screen">
      <main className="flex-1 overflow-auto py-4 px-4 bg-gray-100 w-[100%]">
        <div className="flex space-x-4">
          <div className="w-1/3">
            <h2 className="mb-4 text-sm font-medium text-gray-400 dark:text-gray-300 flex items-center">
              <BackpackIcon className="mr-2 h-4 w-4" />
              Backlog
            </h2>
          </div>
          <div className="w-1/3">
            <h2 className="mb-4 text-sm font-medium text-gray-400 dark:text-gray-300 flex items-center">
              <ListTodoIcon className="mr-2 h-4 w-4" />
              To Do
            </h2>
            <div className="bg-white p-3 rounded-lg shadow-sm mb-4">
              <h3 className="text-sm font-semibold mb-1">Task 4</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                This is a description for task 4.
              </p>
            </div>
            <div className="bg-white p-3 rounded-lg shadow-sm mb-4">
              <h3 className="text-sm font-semibold mb-1">Task 5</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                This is a description for task 5.
              </p>
            </div>
          </div>
          <div className="w-1/3">
            <h2 className="mb-4 text-sm font-medium text-gray-400 dark:text-gray-300 flex items-center">
              <ActivityIcon className="mr-2 h-4 w-4" />
              In Progress
            </h2>
            <div className="bg-white p-3 rounded-lg shadow-sm mb-4">
              <h3 className="text-sm font-semibold mb-1">Task 6</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                This is a description for task 6.
              </p>
            </div>
            <div className="bg-white p-3 rounded-lg shadow-sm mb-4">
              <h3 className="text-sm font-semibold mb-1">Task 7</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                This is a description for task 7.
              </p>
            </div>
          </div>
          <div className="w-1/3">
            <h2 className="mb-4 text-sm font-medium text-gray-400 dark:text-gray-300 flex items-center">
              <CheckIcon className="mr-2 h-4 w-4" />
              Done
            </h2>
            <div className="bg-white p-3 rounded-lg shadow-sm mb-4">
              <h3 className="text-sm font-semibold mb-1">Task 8</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                This is a description for task 8.
              </p>
            </div>
            <div className="bg-white p-3 rounded-lg shadow-sm mb-4">
              <h3 className="text-sm font-semibold mb-1">Task 9</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                This is a description for task 9.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
