/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TasksLazyImport = createFileRoute('/tasks')()
const ShoppingListLazyImport = createFileRoute('/shopping-list')()
const ProfileLazyImport = createFileRoute('/profile')()
const CalendarLazyImport = createFileRoute('/calendar')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TasksLazyRoute = TasksLazyImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tasks.lazy').then((d) => d.Route))

const ShoppingListLazyRoute = ShoppingListLazyImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/shopping-list.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const CalendarLazyRoute = CalendarLazyImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/calendar.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListLazyImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/calendar': typeof CalendarLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/shopping-list': typeof ShoppingListLazyRoute
  '/tasks': typeof TasksLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/calendar': typeof CalendarLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/shopping-list': typeof ShoppingListLazyRoute
  '/tasks': typeof TasksLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/calendar': typeof CalendarLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/shopping-list': typeof ShoppingListLazyRoute
  '/tasks': typeof TasksLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/profile' | '/shopping-list' | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/profile' | '/shopping-list' | '/tasks'
  id: '__root__' | '/' | '/calendar' | '/profile' | '/shopping-list' | '/tasks'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CalendarLazyRoute: typeof CalendarLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  ShoppingListLazyRoute: typeof ShoppingListLazyRoute
  TasksLazyRoute: typeof TasksLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CalendarLazyRoute: CalendarLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  ShoppingListLazyRoute: ShoppingListLazyRoute,
  TasksLazyRoute: TasksLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calendar",
        "/profile",
        "/shopping-list",
        "/tasks"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/calendar": {
      "filePath": "calendar.lazy.tsx"
    },
    "/profile": {
      "filePath": "profile.lazy.tsx"
    },
    "/shopping-list": {
      "filePath": "shopping-list.lazy.tsx"
    },
    "/tasks": {
      "filePath": "tasks.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
